name: thibaudbdx
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 77.37.87.161
          username: backend_ftp
          password: "(8Nc.IVy&rb1uWBxDitX"
          protocol: ftp
          port: 21
